"""empty message

Revision ID: 6e7d495edeb5
Revises: 9f07a127ece7
Create Date: 2021-03-31 13:06:29.404268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e7d495edeb5'
down_revision = '9f07a127ece7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alamat_pengiriman',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pengiriman', sa.String(length=30), nullable=True),
    sa.Column('alamat_pengiriman', sa.Text(), nullable=False),
    sa.Column('coordinates', sa.Text(), nullable=False),
    sa.Column('lattitude', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('nama_pengguna', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_aktif', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['nama_pengguna'], ['kurir.id'], name='user_nama_pengguna_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.drop_table('alamat_pengiriman')
    # ### end Alembic commands ###
